CONTROL_ATTRIBUTES = {
    "generation.mode": "mode",
    "generation.aspect_ratio": "aspect",
    "generation.resolution": "res_class",
    "generation.resolved_resolution": "resolved",
    "generation.frames": "frames",
    "generation.steps": "steps",
    "generation.seed": "seed",
    "generation.prompt": "prompt",
    "generation.scroll": "generation_scroll",
    "generation.references.group": "ref_group",
    "generation.references.images.add": "tutorial_ref_images_add",
    "generation.references.images.list": "ref_images.list",
    "generation.references.images.preview": "tutorial_ref_images_preview",
    "generation.lora1.path": "tutorial_lora1_path",
    "generation.lora1.browse": "tutorial_lora1_browse",
    "generation.lora1.strength": "tutorial_lora1_strength",
    "generation.lora2.path": "tutorial_lora2_path",
    "generation.lora2.browse": "tutorial_lora2_browse",
    "generation.lora2.strength": "tutorial_lora2_strength",
    "generation.lora3.path": "tutorial_lora3_path",
    "generation.lora3.browse": "tutorial_lora3_browse",
    "generation.lora3.strength": "tutorial_lora3_strength",
    "generation.advanced.cfg": "cfg",
    "generation.advanced.video_shift": "shift",
    "generation.advanced.audio_shift": "audio_shift",
    "generation.advanced.sampler": "sampler",
    "generation.advanced.scheduler": "scheduler",
    "generation.safe_preset": "safe_preset_button",
    "generation.generate": "gen",
    "generation.cancel": "cancel",
    "generation.open_output_folder": "openout",
    "queue.summary": "queue_summary",
    "queue.running": "running_tree",
    "queue.pending": "pending_tree",
    "queue.finished": "finished_tree",
    "queue.finished.first": "finished_tree",
    "queue.finished.last": "finished_tree",
    "settings.output_folder": "output_folder.edit",
    "settings.output_name": "output_name",
    "settings.play_result": "play_result_finished",
    "settings.use_hybrid_model": "use_hybrid_model",
    "settings.fl2va_model.path": "fl2va_model.edit",
    "settings.ref2va_model.path": "ref2va_model.edit",
    "prompt_builder.status": "builder_status",
}

TAB_TITLES = {
    "app.tabs.generation": "Generation",
    "app.tabs.prompt_builder": "Prompt Builder",
    "app.tabs.queue": "Queue",
    "app.tabs.music_clip_creator": "Music Clip Creator",
    "app.tabs.settings": "Settings",
}
